apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging

resources:
- ../../base-manifests
- service.yml
- namespace.yml
- ingress.yml

    # change the label for pod affinity
    # change the label for pod affinity
patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: tech-challenge-staging
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/metadata/labels/app
      value: tech-challenge-staging
    - op: replace
      path: /spec/selector/matchLabels/app
      value: tech-challenge-staging
    # change the label for pod affinity
    - op: replace
      path: /spec/template/spec/affinity/podAntiAffinity/requiredDuringSchedulingIgnoredDuringExecution/0/labelSelector/matchExpressions/0/values/0
      value: tech-challenge-prod
  target:
    kind: Deployment
    name: base-deployment
    version: v1

images:
- name: 309457222015.dkr.ecr.us-east-1.amazonaws.com/tech_challenge_arnold
  newTag: 5e0c329048d33c5dfc944d4630978bbf5033636a
