apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod

resources:
- ../../base-manifests
- service.yml
- namespace.yml

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: tech-challenge-prod
    - op: replace
      path: /spec/replicas
      value: 2
    # change the label for service selector
    - op: replace
      path: /spec/template/metadata/labels/app
      value: tech-challenge-prod
    # change the label for pod selector
    - op: replace
      path: /spec/selector/matchLabels/app
      value: tech-challenge-prod
    # change the label for pod affinity
    - op: replace
      path: /spec/template/spec/affinity/podAntiAffinity/requiredDuringSchedulingIgnoredDuringExecution/0/labelSelector/matchExpressions/0/values/0
      value: tech-challenge-prod
  target:
    kind: Deployment
    name: base-deployment
    version: v1

images:
- name: 309457222015.dkr.ecr.us-east-1.amazonaws.com/tech_challenge_arnold
  newTag: v1
