name: Test and Lint

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - '**.md'
      - '**.yml'
  workflow_call:

jobs:
  python-lint:
    name: Application Linter
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache pip packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('docker/requirements.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docker/requirements.txt
          pip install pylint
          pip install pytest
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')

  test:
    name: Run python tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache pip packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('docker/requirements.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docker/requirements.txt
          pip install pylint
          pip install pytest
      - name: Run unit tests
        run: |
          pytest

  yaml-lint:
    name: YAML Linter
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install yamllint
      - name: Analysing the code with yamllint
        run: |
          yamllint .
