name: Test and Lint

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - '**.md'
      - '**.yml'
  workflow_call:

jobs:
  dependencies:
    name: Install dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Cache pip packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('docker/requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docker/requirements.txt
          pip install pylint
          pip install pytest

  lint:
    name: Application Linter
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: dependencies
    steps:
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')

  test:
    name: Run python tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: dependencies
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - name: Run unit tests
        run: |
          pytest
